// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: imdbproto/imdb_service.proto

package imdbprotopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_imdbproto_imdb_service_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_imdbproto_imdb_service_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_imdbproto_imdb_service_proto_rawDescGZIP(), []int{0}
}

type RequestAddPerson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email  string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Age    int32  `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Gender Gender `protobuf:"varint,4,opt,name=gender,proto3,enum=imdbproto.Gender" json:"gender,omitempty"`
	Phone  string `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
}

func (x *RequestAddPerson) Reset() {
	*x = RequestAddPerson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imdbproto_imdb_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAddPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddPerson) ProtoMessage() {}

func (x *RequestAddPerson) ProtoReflect() protoreflect.Message {
	mi := &file_imdbproto_imdb_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddPerson.ProtoReflect.Descriptor instead.
func (*RequestAddPerson) Descriptor() ([]byte, []int) {
	return file_imdbproto_imdb_service_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAddPerson) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RequestAddPerson) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestAddPerson) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RequestAddPerson) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *RequestAddPerson) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ResponseAddPerson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Person *Person `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
}

func (x *ResponseAddPerson) Reset() {
	*x = ResponseAddPerson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imdbproto_imdb_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAddPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAddPerson) ProtoMessage() {}

func (x *ResponseAddPerson) ProtoReflect() protoreflect.Message {
	mi := &file_imdbproto_imdb_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAddPerson.ProtoReflect.Descriptor instead.
func (*ResponseAddPerson) Descriptor() ([]byte, []int) {
	return file_imdbproto_imdb_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAddPerson) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flat    string `protobuf:"bytes,1,opt,name=Flat,proto3" json:"Flat,omitempty"`
	Street  string `protobuf:"bytes,2,opt,name=Street,proto3" json:"Street,omitempty"`
	PinCode int32  `protobuf:"varint,3,opt,name=PinCode,proto3" json:"PinCode,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imdbproto_imdb_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_imdbproto_imdb_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_imdbproto_imdb_service_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetFlat() string {
	if x != nil {
		return x.Flat
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetPinCode() int32 {
	if x != nil {
		return x.PinCode
	}
	return 0
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Email  string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Age    int32  `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	Gender Gender `protobuf:"varint,5,opt,name=gender,proto3,enum=imdbproto.Gender" json:"gender,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imdbproto_imdb_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_imdbproto_imdb_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_imdbproto_imdb_service_proto_rawDescGZIP(), []int{3}
}

func (x *Person) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Person) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

type SearchPersonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
}

func (x *SearchPersonRequest) Reset() {
	*x = SearchPersonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imdbproto_imdb_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPersonRequest) ProtoMessage() {}

func (x *SearchPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imdbproto_imdb_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPersonRequest.ProtoReflect.Descriptor instead.
func (*SearchPersonRequest) Descriptor() ([]byte, []int) {
	return file_imdbproto_imdb_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchPersonRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ResponseAddManyPerson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ResponseAddManyPerson) Reset() {
	*x = ResponseAddManyPerson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imdbproto_imdb_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAddManyPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAddManyPerson) ProtoMessage() {}

func (x *ResponseAddManyPerson) ProtoReflect() protoreflect.Message {
	mi := &file_imdbproto_imdb_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAddManyPerson.ProtoReflect.Descriptor instead.
func (*ResponseAddManyPerson) Descriptor() ([]byte, []int) {
	return file_imdbproto_imdb_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseAddManyPerson) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_imdbproto_imdb_service_proto protoreflect.FileDescriptor

var file_imdbproto_imdb_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6d, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6d, 0x64, 0x62,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x69, 0x6d, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x10, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x69, 0x6d, 0x64,
	0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x3e, 0x0a, 0x11, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x12, 0x29, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x69, 0x6d, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x52, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x6c, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x72, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x72, 0x65,
	0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x7f, 0x0a, 0x06,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41,
	0x67, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x11, 0x2e, 0x69, 0x6d, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x2b, 0x0a,
	0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x22, 0x2d, 0x0a, 0x15, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x6e, 0x79, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x44, 0x0a, 0x06, 0x47, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x12, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x47,
	0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d,
	0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x02, 0x32,
	0xbb, 0x02, 0x0a, 0x0b, 0x49, 0x6d, 0x64, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x48, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x69,
	0x6d, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x1a, 0x1c, 0x2e, 0x69, 0x6d, 0x64, 0x62,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64,
	0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0d, 0x41, 0x64, 0x64,
	0x4d, 0x61, 0x6e, 0x79, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x69, 0x6d, 0x64,
	0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x64,
	0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x1a, 0x20, 0x2e, 0x69, 0x6d, 0x64, 0x62, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x64, 0x64, 0x4d,
	0x61, 0x6e, 0x79, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x00, 0x28, 0x01, 0x12, 0x43, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x69, 0x6d,
	0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x69, 0x6d,
	0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x49, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x2e, 0x69, 0x6d, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x69, 0x6d, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x42, 0x5a,
	0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x68, 0x61, 0x6e,
	0x61, 0x6e, 0x6a, 0x61, 0x79, 0x6b, 0x73, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x2f, 0x64, 0x6b, 0x67,
	0x6f, 0x73, 0x71, 0x6c, 0x69, 0x6d, 0x64, 0x62, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6d, 0x64, 0x62,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x69, 0x6d, 0x64, 0x62, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_imdbproto_imdb_service_proto_rawDescOnce sync.Once
	file_imdbproto_imdb_service_proto_rawDescData = file_imdbproto_imdb_service_proto_rawDesc
)

func file_imdbproto_imdb_service_proto_rawDescGZIP() []byte {
	file_imdbproto_imdb_service_proto_rawDescOnce.Do(func() {
		file_imdbproto_imdb_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_imdbproto_imdb_service_proto_rawDescData)
	})
	return file_imdbproto_imdb_service_proto_rawDescData
}

var file_imdbproto_imdb_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_imdbproto_imdb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_imdbproto_imdb_service_proto_goTypes = []interface{}{
	(Gender)(0),                   // 0: imdbproto.Gender
	(*RequestAddPerson)(nil),      // 1: imdbproto.RequestAddPerson
	(*ResponseAddPerson)(nil),     // 2: imdbproto.ResponseAddPerson
	(*Address)(nil),               // 3: imdbproto.Address
	(*Person)(nil),                // 4: imdbproto.Person
	(*SearchPersonRequest)(nil),   // 5: imdbproto.SearchPersonRequest
	(*ResponseAddManyPerson)(nil), // 6: imdbproto.ResponseAddManyPerson
}
var file_imdbproto_imdb_service_proto_depIdxs = []int32{
	0, // 0: imdbproto.RequestAddPerson.gender:type_name -> imdbproto.Gender
	4, // 1: imdbproto.ResponseAddPerson.person:type_name -> imdbproto.Person
	0, // 2: imdbproto.Person.gender:type_name -> imdbproto.Gender
	1, // 3: imdbproto.ImdbService.AddPerson:input_type -> imdbproto.RequestAddPerson
	1, // 4: imdbproto.ImdbService.AddManyPerson:input_type -> imdbproto.RequestAddPerson
	5, // 5: imdbproto.ImdbService.ListPerson:input_type -> imdbproto.SearchPersonRequest
	5, // 6: imdbproto.ImdbService.ListPersonById:input_type -> imdbproto.SearchPersonRequest
	2, // 7: imdbproto.ImdbService.AddPerson:output_type -> imdbproto.ResponseAddPerson
	6, // 8: imdbproto.ImdbService.AddManyPerson:output_type -> imdbproto.ResponseAddManyPerson
	4, // 9: imdbproto.ImdbService.ListPerson:output_type -> imdbproto.Person
	4, // 10: imdbproto.ImdbService.ListPersonById:output_type -> imdbproto.Person
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_imdbproto_imdb_service_proto_init() }
func file_imdbproto_imdb_service_proto_init() {
	if File_imdbproto_imdb_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_imdbproto_imdb_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAddPerson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imdbproto_imdb_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAddPerson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imdbproto_imdb_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imdbproto_imdb_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imdbproto_imdb_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPersonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imdbproto_imdb_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAddManyPerson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imdbproto_imdb_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imdbproto_imdb_service_proto_goTypes,
		DependencyIndexes: file_imdbproto_imdb_service_proto_depIdxs,
		EnumInfos:         file_imdbproto_imdb_service_proto_enumTypes,
		MessageInfos:      file_imdbproto_imdb_service_proto_msgTypes,
	}.Build()
	File_imdbproto_imdb_service_proto = out.File
	file_imdbproto_imdb_service_proto_rawDesc = nil
	file_imdbproto_imdb_service_proto_goTypes = nil
	file_imdbproto_imdb_service_proto_depIdxs = nil
}
