# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imdbproto/imdb_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imdbproto/imdb_service.proto',
  package='imdbproto',
  syntax='proto3',
  serialized_options=_b('Z@github.com/dhananjayksharma/dkgosqlimdbapi/imdbproto;imdbprotopb'),
  serialized_pb=_b('\n\x1cimdbproto/imdb_service.proto\x12\timdbproto\"n\n\x10RequestAddPerson\x12\r\n\x05\x45mail\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0b\n\x03\x41ge\x18\x03 \x01(\x05\x12!\n\x06gender\x18\x04 \x01(\x0e\x32\x11.imdbproto.Gender\x12\r\n\x05Phone\x18\x05 \x01(\t\"6\n\x11ResponseAddPerson\x12!\n\x06person\x18\x01 \x01(\x0b\x32\x11.imdbproto.Person\"8\n\x07\x41\x64\x64ress\x12\x0c\n\x04\x46lat\x18\x01 \x01(\t\x12\x0e\n\x06Street\x18\x02 \x01(\t\x12\x0f\n\x07PinCode\x18\x03 \x01(\x05\"a\n\x06Person\x12\n\n\x02Id\x18\x01 \x01(\t\x12\r\n\x05\x45mail\x18\x02 \x01(\t\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0b\n\x03\x41ge\x18\x04 \x01(\x05\x12!\n\x06gender\x18\x05 \x01(\x0e\x32\x11.imdbproto.Gender\"$\n\x13SearchPersonRequest\x12\r\n\x05Query\x18\x01 \x01(\t\"&\n\x15ResponseAddManyPerson\x12\r\n\x05\x63ount\x18\x01 \x01(\x05*D\n\x06Gender\x12\x16\n\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n\x0bGENDER_MALE\x10\x01\x12\x11\n\rGENDER_FEMALE\x10\x02\x32\xbb\x02\n\x0bImdbService\x12H\n\tAddPerson\x12\x1b.imdbproto.RequestAddPerson\x1a\x1c.imdbproto.ResponseAddPerson\"\x00\x12R\n\rAddManyPerson\x12\x1b.imdbproto.RequestAddPerson\x1a .imdbproto.ResponseAddManyPerson\"\x00(\x01\x12\x43\n\nListPerson\x12\x1e.imdbproto.SearchPersonRequest\x1a\x11.imdbproto.Person\"\x00\x30\x01\x12I\n\x0eListPersonById\x12\x1e.imdbproto.SearchPersonRequest\x1a\x11.imdbproto.Person\"\x00(\x01\x30\x01\x42\x42Z@github.com/dhananjayksharma/dkgosqlimdbapi/imdbproto;imdbprotopbb\x06proto3')
)

_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='imdbproto.Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GENDER_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENDER_MALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENDER_FEMALE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=446,
  serialized_end=514,
)
_sym_db.RegisterEnumDescriptor(_GENDER)

Gender = enum_type_wrapper.EnumTypeWrapper(_GENDER)
GENDER_UNSPECIFIED = 0
GENDER_MALE = 1
GENDER_FEMALE = 2



_REQUESTADDPERSON = _descriptor.Descriptor(
  name='RequestAddPerson',
  full_name='imdbproto.RequestAddPerson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Email', full_name='imdbproto.RequestAddPerson.Email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='imdbproto.RequestAddPerson.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Age', full_name='imdbproto.RequestAddPerson.Age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='imdbproto.RequestAddPerson.gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Phone', full_name='imdbproto.RequestAddPerson.Phone', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=153,
)


_RESPONSEADDPERSON = _descriptor.Descriptor(
  name='ResponseAddPerson',
  full_name='imdbproto.ResponseAddPerson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='imdbproto.ResponseAddPerson.person', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=209,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='imdbproto.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Flat', full_name='imdbproto.Address.Flat', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Street', full_name='imdbproto.Address.Street', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PinCode', full_name='imdbproto.Address.PinCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=267,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='imdbproto.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='imdbproto.Person.Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Email', full_name='imdbproto.Person.Email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='imdbproto.Person.Name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Age', full_name='imdbproto.Person.Age', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='imdbproto.Person.gender', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=366,
)


_SEARCHPERSONREQUEST = _descriptor.Descriptor(
  name='SearchPersonRequest',
  full_name='imdbproto.SearchPersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Query', full_name='imdbproto.SearchPersonRequest.Query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=404,
)


_RESPONSEADDMANYPERSON = _descriptor.Descriptor(
  name='ResponseAddManyPerson',
  full_name='imdbproto.ResponseAddManyPerson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='imdbproto.ResponseAddManyPerson.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=444,
)

_REQUESTADDPERSON.fields_by_name['gender'].enum_type = _GENDER
_RESPONSEADDPERSON.fields_by_name['person'].message_type = _PERSON
_PERSON.fields_by_name['gender'].enum_type = _GENDER
DESCRIPTOR.message_types_by_name['RequestAddPerson'] = _REQUESTADDPERSON
DESCRIPTOR.message_types_by_name['ResponseAddPerson'] = _RESPONSEADDPERSON
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['SearchPersonRequest'] = _SEARCHPERSONREQUEST
DESCRIPTOR.message_types_by_name['ResponseAddManyPerson'] = _RESPONSEADDMANYPERSON
DESCRIPTOR.enum_types_by_name['Gender'] = _GENDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestAddPerson = _reflection.GeneratedProtocolMessageType('RequestAddPerson', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTADDPERSON,
  __module__ = 'imdbproto.imdb_service_pb2'
  # @@protoc_insertion_point(class_scope:imdbproto.RequestAddPerson)
  ))
_sym_db.RegisterMessage(RequestAddPerson)

ResponseAddPerson = _reflection.GeneratedProtocolMessageType('ResponseAddPerson', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEADDPERSON,
  __module__ = 'imdbproto.imdb_service_pb2'
  # @@protoc_insertion_point(class_scope:imdbproto.ResponseAddPerson)
  ))
_sym_db.RegisterMessage(ResponseAddPerson)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESS,
  __module__ = 'imdbproto.imdb_service_pb2'
  # @@protoc_insertion_point(class_scope:imdbproto.Address)
  ))
_sym_db.RegisterMessage(Address)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'imdbproto.imdb_service_pb2'
  # @@protoc_insertion_point(class_scope:imdbproto.Person)
  ))
_sym_db.RegisterMessage(Person)

SearchPersonRequest = _reflection.GeneratedProtocolMessageType('SearchPersonRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHPERSONREQUEST,
  __module__ = 'imdbproto.imdb_service_pb2'
  # @@protoc_insertion_point(class_scope:imdbproto.SearchPersonRequest)
  ))
_sym_db.RegisterMessage(SearchPersonRequest)

ResponseAddManyPerson = _reflection.GeneratedProtocolMessageType('ResponseAddManyPerson', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEADDMANYPERSON,
  __module__ = 'imdbproto.imdb_service_pb2'
  # @@protoc_insertion_point(class_scope:imdbproto.ResponseAddManyPerson)
  ))
_sym_db.RegisterMessage(ResponseAddManyPerson)


DESCRIPTOR._options = None

_IMDBSERVICE = _descriptor.ServiceDescriptor(
  name='ImdbService',
  full_name='imdbproto.ImdbService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=517,
  serialized_end=832,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddPerson',
    full_name='imdbproto.ImdbService.AddPerson',
    index=0,
    containing_service=None,
    input_type=_REQUESTADDPERSON,
    output_type=_RESPONSEADDPERSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddManyPerson',
    full_name='imdbproto.ImdbService.AddManyPerson',
    index=1,
    containing_service=None,
    input_type=_REQUESTADDPERSON,
    output_type=_RESPONSEADDMANYPERSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListPerson',
    full_name='imdbproto.ImdbService.ListPerson',
    index=2,
    containing_service=None,
    input_type=_SEARCHPERSONREQUEST,
    output_type=_PERSON,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListPersonById',
    full_name='imdbproto.ImdbService.ListPersonById',
    index=3,
    containing_service=None,
    input_type=_SEARCHPERSONREQUEST,
    output_type=_PERSON,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMDBSERVICE)

DESCRIPTOR.services_by_name['ImdbService'] = _IMDBSERVICE

# @@protoc_insertion_point(module_scope)
